project:
  type: website

website:
  title: "Caleb Hallinan"
  favicon: "images/dice_icon.png"
  navbar:
    right:
      - aboutme.qmd
      - projects.qmd
      - talks.qmd
      - blog.qmd
      - cv.qmd

format:
  html:
    theme: darkly
    css: styles.css

editor: visual

execute:
  freeze: auto


